- packages/oruga/src/components/button/Button.vue
- packages/oruga/src/components/checkbox/Checkbox.vue
- packages/oruga/src/components/collapse/Collapse.vue
- packages/oruga/src/components/dropdown/Dropdown.vue
- packages/oruga/src/components/dropdown/DropdownItem.vue
- packages/oruga/src/components/field/Field.vue
- packages/oruga/src/components/icon/Icon.vue
- packages/oruga/src/components/input/Input.vue
- packages/oruga/src/utils/CheckRadioMixin.js
- packages/oruga/src/utils/FormElementMixin.js
This PR adds some documentation. Hope it helps!
> Doc update

- package-lock.json
- package.json
- packages/docs/.prettierrc
- packages/docs/.vuepress/config.js
- packages/docs/components/Autocomplete.md
- packages/docs/components/Button.md
- packages/docs/components/Checkbox.md
- packages/docs/components/Collapse.md
- packages/docs/components/Dropdown.md
- packages/docs/components/Field.md
- packages/docs/components/Icon.md
- packages/docs/components/Input.md
- packages/docs/components/Loading.md
- packages/docs/components/Modal.md
- packages/docs/components/Pagination.md
- packages/docs/components/Radio.md
- packages/docs/components/Select.md
- packages/docs/components/Sidebar.md
- packages/docs/components/Skeleton.md
- packages/docs/components/Slider.md
- packages/docs/components/Switch.md
- packages/docs/components/Table.md
- packages/docs/components/Tooltip.md
- packages/docs/package-lock.json
- packages/docs/package.json
- packages/oruga-tailwindcss/package-lock.json
- packages/oruga/package-lock.json
> Add integration to codepen

- packages/oruga/nuxt/index.js
- packages/oruga/package.json
> Include 'nuxt' to package.json files

- .circleci/config.yml
- .github/CONTRIBUTING.md
- .gitignore
- package.json
> New lerna scripts

- packages/docs/documentation/README.md
> [new docs NuxtJS] Update README.md

- .github/CONTRIBUTING.md
> Add command to install lerna

- packages/oruga-next/fix_rollup_vue.sh
- packages/oruga-next/rollup_plugin_vue/index.d.ts
- packages/oruga-next/rollup_plugin_vue/index.js
After modules installation run
```
./fix_rollup_vue.sh
```
> Add script to fix Rollup Plugin Vue

- packages/oruga/src/components/slider/Slider.vue
- packages/oruga/src/components/slider/SliderThumb.vue
> feat: show value inside slider optional

- packages/oruga/src/scss/components/_steps.scss
> fix aligned vertical step

- packages/oruga-next/types/index.d.ts
> Add initial TypeScript support for oruga-next

- .editorconfig
- packages/oruga/src/scss/components/_autocomplete.scss
- packages/oruga/src/scss/components/_button.scss
- packages/oruga/src/scss/components/_checkbox.scss
- packages/oruga/src/scss/components/_dialog.scss
- packages/oruga/src/scss/components/_dropdown.scss
- packages/oruga/src/scss/components/_field.scss
- packages/oruga/src/scss/components/_icon.scss
- packages/oruga/src/scss/components/_input.scss
- packages/oruga/src/scss/components/_loading.scss
- packages/oruga/src/scss/components/_modal.scss
- packages/oruga/src/scss/components/_pagination.scss
- packages/oruga/src/scss/components/_radio.scss
- packages/oruga/src/scss/components/_select.scss
- packages/oruga/src/scss/components/_sidebar.scss
- packages/oruga/src/scss/components/_skeleton.scss
- packages/oruga/src/scss/components/_slider.scss
- packages/oruga/src/scss/components/_steps.scss
- packages/oruga/src/scss/components/_switch.scss
- packages/oruga/src/scss/components/_table.scss
- packages/oruga/src/scss/components/_tabs.scss
- packages/oruga/src/scss/components/_tooltip.scss
- packages/oruga/src/scss/components/_upload.scss
- packages/oruga/src/scss/oruga.scss
- packages/oruga/src/scss/utilities/_expressions.scss
- packages/oruga/src/scss/utilities/_helpers.scss
This PR refactors Oruga helpers for a better development experience
- Refactoring helpers for a better expression calculation
- Refactoring helpers for better mixins/functions name
- Add .editorconfig to keep code style across contributors
> Refactoring helpers

- packages/oruga-next/src/components/checkbox/Checkbox.vue
- packages/oruga-next/src/components/radio/Radio.vue
- packages/oruga-next/src/components/table/Table.vue
- packages/oruga/src/components/checkbox/Checkbox.vue
- packages/oruga/src/components/radio/Radio.vue
- packages/oruga/src/components/table/Table.vue
> Use input instead of native click for table checkboxes. Fixes #81

- packages/oruga/src/scss/utilities/_animations.scss
This fixes the fade animation (used by the loading component)
> Fix typo in fade animation

- packages/docs/documentation/README.md
> Correct typo in README.md

- packages/docs/components/Table.md
- packages/oruga-next/src/components/table/Table.vue
- packages/oruga-next/src/components/table/TableColumn.vue
- packages/oruga/.eslintrc.js
- packages/oruga/src/components/datepicker/__snapshots__/Datepicker.spec.js.snap
- packages/oruga/src/components/steps/__snapshots__/Steps.spec.js.snap
- packages/oruga/src/components/table/Table.vue
- packages/oruga/src/components/table/TableColumn.vue
- packages/oruga/src/components/table/examples/Table.md
> fix: enable default sorting on OTable (fixes #106)

- packages/oruga-next/src/components/radio/Radio.vue
- packages/oruga-next/src/components/slider/SliderThumb.vue
Fixes #117 
- Migrate `this.value` to `this.modelValue`
> Migrate this.value to this.modelValue

- packages/oruga-next/src/components/select/Select.vue
Fixes #121 
- Add the `selectClass` prop definition to the Select component.
Note I haven't been able to test this yet
> Add selectClass prop

- packages/oruga/src/components/icon/examples/Icon.md
Fixes #
A few copy fixes only
-
-
-
> Fixes some grammatical errors in the icon docs

- packages/oruga-next/src/index.ts
Fixes #168
- reuse $oruga for provide/inject
- use "oruga" as name for provide/inject
> feat: provide programmatic usage

- packages/docs/components/Button.md
- packages/oruga-next/src/components/button/Button.vue
- packages/oruga/src/components/button/Button.spec.js
- packages/oruga/src/components/button/Button.vue
- packages/oruga/src/components/button/Inspector.vue
> feat: add icon right and left classes properties for button

- packages/docs/components/Tabs.md
- packages/oruga-next/src/components/tabs/TabItem.vue
- packages/oruga-next/src/components/tabs/Tabs.vue
- packages/oruga/src/components/datepicker/__snapshots__/Datepicker.spec.js.snap
- packages/oruga/src/components/dropdown/__snapshots__/Dropdown.spec.js.snap
- packages/oruga/src/components/dropdown/__snapshots__/DropdownItem.spec.js.snap
- packages/oruga/src/components/loading/__snapshots__/Loading.spec.js.snap
- packages/oruga/src/components/modal/__snapshots__/Modal.spec.js.snap
- packages/oruga/src/components/radio/__snapshots__/Radio.spec.js.snap
- packages/oruga/src/components/tabs/TabItem.spec.js
- packages/oruga/src/components/tabs/TabItem.vue
- packages/oruga/src/components/tabs/Tabs.vue
- packages/oruga/src/components/tabs/__snapshots__/Tabs.spec.js.snap
- packages/oruga/src/components/tabs/examples/Tabs.md
- packages/oruga/src/components/timepicker/__snapshots__/Timepicker.spec.js.snap
> Add support for tag in TabsItem

- packages/oruga-next/src/components/table/Table.vue
- packages/oruga-next/src/components/table/TablePagination.vue
- packages/oruga/src/components/table/Table.vue
- packages/oruga/src/components/table/TablePagination.vue
This PR adds the missing imports and remove the unnecessary ones.
> Import `OPagination` in `OTablePagination`

- packages/docs/components/Table.md
- packages/oruga-next/src/components/table/Table.vue
- packages/oruga-next/src/components/table/TableColumn.vue
- packages/oruga/src/components/table/Table.vue
- packages/oruga/src/components/table/TableColumn.vue
Fixes #
This PR adds scoped slots for a subheader to the table component.
Addresses issue #92.
Added subheader scoped slot to the table component for both oruga and oruga-next.
- Added element to contain the subheader
- Added function hasCustomSubheader to hide/show slot if there is/is not a subheader.
> Add scoped slot for Subheader to Table Component

- packages/oruga-next/src/components/autocomplete/Autocomplete.vue
- packages/oruga-next/src/components/datepicker/Datepicker.vue
- packages/oruga-next/src/components/input/Input.vue
- packages/oruga-next/src/components/table/Table.vue
- packages/oruga-next/src/components/table/TableColumn.vue
> fix: removed ts artifacts(leftovers)

- packages/oruga-next/src/components/carousel/CarouselItem.vue
Fixes  make CarouselItem configurable
> fix: carousel config

- packages/oruga-next/src/components/modal/Modal.vue
- packages/oruga/src/components/modal/Modal.vue
Fixes #279
- Fix full-screen modals not being full screen
> (fix)full-screen modals not being full screen

- packages/oruga-next/src/components/loading/index.ts
- packages/oruga-next/src/components/modal/index.ts
- packages/oruga-next/src/components/notification/index.ts
Fixes #313 
- fixes the Vue3 "open" functions to return the component "instance" (aka the proxy)
> Correct return value of programmatic open methods in Vue 3 to return component instance

- packages/oruga/src/components/table/Table.spec.js
Added testcases for table component and increase code coverage of it.
Before PR:
After PR:
> Added testcases for table component

- packages/docs-next/.vitepress/theme/examples/sidebar/inspector.vue
- packages/oruga-next/src/components/sidebar/Sidebar.vue
- packages/oruga/src/components/sidebar/Inspector.vue
- packages/oruga/src/components/sidebar/Sidebar.vue
Implements #435
adds hiddenClass and visibleClass to Sidebar component
> Add Sidebar hidden/visible Classes 

- packages/docs-next/components/Table.md
- packages/oruga-next/src/components/table/TableColumn.vue
Fixes #440 
Update Table documentation:
* Update section navigation 
* Add Table-Column props & slots
> update table documentation

- package-lock.json
- packages/oruga/src/scss/components/_tooltip.scss
Fixes #
- Adding `!default` to `$tooltip-content-multiline-width` SCSS var
-
-
-
> adding default to tooltip-content-multiline-width SCSS var

- packages/oruga-next/src/components/button/Button.vue
- packages/oruga/src/scss/components/_button.scss
added: loading props for button
Very helpful when running an ajax request on button click
> added: loading props for button

- .github/CONTRIBUTING.md
Fixes #
- Added some clarifications in the `CONTRIBUTING.md` file to help less experienced programmers to make their first contribution.
> docs: improve contributing file

- packages/oruga-next/src/components/switch/Switch.vue
- packages/oruga/src/components/switch/Switch.spec.js
- packages/oruga/src/components/switch/Switch.vue
- packages/oruga/src/components/switch/__snapshots__/Switch.spec.js.snap
Fixes #484
- The input of component Switch has the role switch (breaking change)
- Added a test
> fix(switch): the role is switch

- packages/docs/components/Menu.md
Hello everyone!
I came across issue #488 and decided to open a PR with the fix.
I fetched the original content of the component in one of the past commits.
Fixes #488
> Fix Issue #488

- packages/oruga-next/src/components/table/Table.vue
- packages/oruga/src/components/table/Table.vue
> Fix Table Pagination Size

- packages/docs-next/components/Steps.md
- packages/oruga/src/scss/components/_steps.scss
Fixes #451
- Update the docs
- Allow divider colors to be set by css variables
- Allow divider colors to be set by sass variables
sass variables may need some additional work
> feat: add a way to style step dividers 

- packages/oruga-next/src/components/radio/Radio.vue
Fixes #572
add  missing checkedClass prop
> fix(radio): add checkedClass prop

- packages/oruga-next/src/components/modal/index.ts
> Remove console.log statement in ModalProgrammatic

- packages/oruga-next/src/components/table/Table.vue
Fix table pagination wrong size property.
> fix(table): fix missing paginationSize

- CHANGELOG.md
- README.md
- package.json
- packages/docs-next/package-lock.json
- packages/docs-next/package.json
- packages/docs/package-lock.json
- packages/docs/package.json
- packages/oruga-next/package-lock.json
- packages/oruga-next/package.json
- packages/oruga/package-lock.json
- packages/oruga/package.json
> chore: release 0.7.0

- packages/docs-next/components/Select.md
- packages/oruga-next/src/components/select/Select.vue
- fix select modelValue prop type
> fix: select vmodel prop type

- packages/docs-next/.vitepress/theme/examples/carousel/custom-indicators.vue
- packages/docs-next/.vitepress/theme/examples/carousel/customise.vue
- packages/docs-next/.vitepress/theme/examples/carousel/list.vue
- packages/docs-next/components/Carousel.md
- packages/oruga-next/src/components/carousel/Carousel.vue
- packages/oruga-next/src/components/carousel/CarouselItem.vue
- packages/oruga-next/src/components/carousel/index.ts
- packages/oruga-next/src/composables/index.ts
- packages/oruga-next/src/composables/useParentProvider.ts
This is part of https://github.com/oruga-ui/oruga/issues/606
In this PR I refactored the carousel component from Options-API to Composition-API.
- Updated Carousel to composition api
- Refactor `InjectChildMixin` and `ProvideParentMixin` into composable
- update docs
> refactor(carousel): update component

- packages/oruga-next/src/composables/useMatchMedia.ts
> fix(mobile): matchmedia

- packages/oruga-next/src/components/autocomplete/Autocomplete.vue
- packages/oruga-next/src/components/carousel/Carousel.vue
- packages/oruga-next/src/composables/useEventListener.ts
- packages/oruga-next/src/composables/useInputHandler.ts
- packages/oruga-next/src/composables/useProgrammatic.ts
- packages/oruga-next/src/utils/helpers.ts
- add some window undefined checks
> feat: add window undefined checks

- packages/oruga-next/src/components/skeleton/Skeleton.vue
- fix skeleton computed item style
> fix(skeleton): fix item style

- packages/docs-next/.vitepress/theme/components/Carbon.vue
- packages/oruga-next/src/components/carousel/Carousel.vue
- packages/oruga-next/src/composables/useMatchMedia.ts
- packages/oruga-next/src/utils/PositionWrapper.vue
- fix window not defined for ssr build
> fix: ssr window not defined

- packages/oruga-next/package.json
- packages/oruga-next/src/index.ts
Fixes #678
- fix export type path
> build: fix types export

- CHANGELOG.md
- package-lock.json
- package.json
- packages/docs-next/package-lock.json
- packages/docs-next/package.json
- packages/oruga-next/package-lock.json
- packages/oruga-next/package.json
> chore: update version v0.8.1

- packages/oruga-next/src/components/loading/LoadingProgrammatic.ts
- packages/oruga-next/src/components/modal/ModalProgrammatic.ts
- packages/oruga-next/src/components/notification/NotificationProgrammatic.ts
- packages/oruga-next/src/components/sidebar/SidebarProgrammatic.ts
> fix(programmatic): adjust open params type

- packages/docs-next/.vitepress/theme/examples/upload/base.vue
- packages/docs-next/components/Upload.md
- packages/oruga-next/src/components/upload/Upload.vue
fix upload "Maximum call stack size exceeded."
- update upload click handler
> fix(upload): update click handler

- .scripts/gen-component-declaration.mjs
> fix(types): fix volar type generation

- README.md
- packages/docs-next/documentation/index.md
Fixes #710
- remove "@oruga-ui/oruga-next/dist/oruga.css" documentation" from documentation
- update README.md
> chore: update readme

- .github/workflows/build-next.yml
- .github/workflows/commit-lint.yml
- .github/workflows/publish-release.yml
- .github/workflows/ts-next-check.yml
> chore: update github actions

- packages/oruga-next/src/components/datepicker/Datepicker.vue
fix(datepicker): datepicker component shows wrong year range when adding max date and min date props
> fix(datepicker): datepicker component shows wrong year range when adding max date and min date props

- packages/oruga-next/src/components/table/TableColumn.vue
Fixes #736
See source-code (one line only)
> Fixed: source of thAttrsData

- packages/oruga-next/src/components/slider/Slider.vue
- packages/oruga-next/src/components/slider/SliderThumb.vue
found some `this` references which i might missed during the refactoring
> fix(slider): remove `this` references

- .scripts/gen-component-declaration.mjs
- packages/docs-next/.vitepress/theme/examples/pagination/base.vue
- packages/docs-next/tsconfig.json
- packages/docs-next/volar.d.ts
Enhance docs development by adding oruga main package volar types to docs tsconfig
> docs: add tsconfig volar types

- packages/oruga-next/src/components/notification/NotificationNotice.vue
Fixes #734
- adjust querySelector from programmatic usage
> fix(notification): adjust querySelector

- packages/oruga-next/src/components/carousel/Carousel.vue
- fix switchTo index while repeat is active
> fix(carousel): fix repeat index

- packages/oruga-next/src/components/dropdown/Dropdown.vue
- packages/oruga-next/src/components/taginput/Taginput.vue
> fix(taginput): fix rootClass inheritance

- packages/oruga-next/src/components/datetimepicker/Datetimepicker.vue
Fixes #784 
- Adjust datetimepicker vmodel handling
> fix(datetimepicker): fix vmodel reactivity

- packages/oruga-next/src/components/autocomplete/Autocomplete.vue
> fix(autocomplete): unselected item autocomplete

- packages/oruga/src/components/datepicker/Datepicker.vue
- packages/oruga/src/components/timepicker/Timepicker.vue
> fix: wrap focus listener into function

- package-lock.json
- packages/docs/.vitepress/theme/components/ThemeSelector.vue
- packages/docs/components/Dropdown.md
- packages/docs/package.json
- packages/oruga/src/components/dropdown/Dropdown.vue
> docs: update bulma theme

- packages/docs/components/Table.md
- packages/oruga/src/components/table/TableColumn.vue
- change searchable slot property `filter` to `filters`
> fix(table): fix table-column searchable slot property bug

- packages/docs/.vitepress/theme/examples/button/base.vue
> docs: update button example

- packages/oruga/src/index.ts
- the ConfigPlugin wasn't exported
> fix(ConfigPlugin): export ConfigPlugin

- packages/oruga/src/components/upload/Upload.vue
Fixes #759
- fix upload v-model bind with prop multiple
> fix(upload): fix upload input bindung

- packages/docs/documentation/index.md
- packages/oruga/package.json
Fixes #839 
- add type to package.json export 
- update docs
> fix(build): add volar types export

- packages/oruga/src/components/loading/LoadingProgrammatic.ts
- packages/oruga/src/components/modal/ModalProgrammatic.ts
- packages/oruga/src/components/notification/NotificationProgrammatic.ts
- packages/oruga/src/components/sidebar/SidebarProgrammatic.ts
- refactor programmatic props naming
> refactor: rename programmatic props type

- packages/docs/.vitepress/theme/components/ThemeSelector.vue
- Changed the text color of the active element to make it prettier 
Before:
After:
> docs: update active text color in theme dropdown

- .scripts/gen-comp-types.mjs
- change `createComponentMetaChecker` to  `createChecker`
> fix: fix type generation script

- packages/docs/.vitepress/theme/examples/autocomplete/objects-array.vue
- packages/oruga/src/components/autocomplete/Autocomplete.vue
- fix openOnFocus, which doesn't get open when there was any selected element
> fix(autocomplete): adjust active state behavior

- packages/oruga/src/components/field/Field.vue
- packages/oruga/src/components/field/tests/__snapshots__/field.test.ts.snap
- packages/oruga/src/components/field/tests/field.test.ts
> test(field): add field tests

- packages/oruga/src/components/field/Field.vue
> fix(field): fix bug when prop `horizontal` is set

- packages/oruga/src/components/taginput/Taginput.vue
Fixes #916
- remove duplicate modelValue setter
> fix(taginput): fix infinite recursive update when updating modeValue

- packages/oruga/src/components/select/types.ts
- packages/oruga/src/components/timepicker/Timepicker.vue
- refactor Timepicker internal Select component options
> refactor(timepicker): adjust select component options

- packages/oruga/src/components/select/Select.vue
- packages/oruga/src/composables/useInputHandler.ts
- Pass the select input ID to the parent field for accessibility labelling
> feat(select): register id to field wrapper

- packages/oruga/src/components/radio/Radio.vue
- add Radio component type generic
> feat(radio): add type generics

- .scripts/gen-volar-dts.mjs
- packages/docs/tsconfig.json
- packages/oruga/components.d.ts
- packages/oruga/src/components/table/examples/detailed.vue
- packages/oruga/tsconfig.json
- add a destict `component.d.ts` file for the main package
> chore: add `component.d.ts` generation

- packages/oruga/src/components/select/Select.vue
- packages/oruga/src/components/select/examples/base.vue
- packages/oruga/src/components/select/examples/multiple.vue
- packages/oruga/src/components/select/props.ts
- packages/oruga/src/components/select/tests/select.test.ts
Part of https://github.com/oruga-ui/oruga/issues/835
**Proposed Changes**
- add conditional type definition for modelValue prop based on multiple prop
> feat(select): make `modelValue` conditional typed by prop `multiple`

- packages/oruga/src/components/upload/Upload.vue
- packages/oruga/src/components/upload/props.ts
Part of https://github.com/oruga-ui/oruga/issues/835
**Proposed Changes**
- add conditional type definition for modelValue prop based on multiple prop
> feat(upload): make `modelValue` conditional typed by prop `mulitple`

- packages/oruga/src/composables/defineClasses.ts
- packages/oruga/src/types/config.ts
- refactor `defineClasses` composable for better readabiltiy
> refactor: `defineClasses` composable

- packages/oruga/src/components/autocomplete/Autocomplete.vue
- packages/oruga/src/components/taginput/Taginput.vue
- fix `keepOpen` behavior while clicking outside
> fix(autocomplete): adjust `keepOpen` behavior

- packages/oruga/src/components/input/examples/base.vue
- packages/oruga/src/components/menu/examples/base.vue
- packages/oruga/src/components/sidebar/examples/base.vue
- packages/oruga/src/components/upload/Upload.vue
- update several examples
- fix upload multiple
> docs: update examples

- packages/oruga/src/composables/defineClasses.ts
- solve an issue when the the class defintion contains an array of strings
> fix(theme): solve issue with class as string array definition

- package-lock.json
- packages/docs/.vitepress/theme/components/ExampleViewer.vue
- packages/docs/components/Autocomplete.md
- packages/docs/components/Dropdown.md
- packages/docs/components/Menu.md
- packages/docs/components/Tabs.md
- packages/docs/package.json
- packages/docs/themes/theme-oruga.md
- update docs bootstrap theme
- update docs oruga theme
> docs(themes): update oruga & bootstrap theme

- packages/oruga/src/components/table/Table.vue
- fix an issue where the value of the `check` and `check-all` event contains the old data. Now these events contain the updated list of checked rows.
> fix(table): solve `check` event reactive value issue

- packages/oruga/src/index.ts
- packages/oruga/src/utils/helpers.ts
- expose Oruga`s helper functions
> build: expose helper functions

- packages/oruga/src/components/steps/Steps.vue
- packages/oruga/src/components/steps/examples/base.vue
- packages/oruga/src/components/steps/examples/index.vue
- packages/oruga/src/components/steps/examples/sizes.vue
- packages/oruga/src/components/tabs/examples/vertical.vue
- packages/oruga/src/components/types.ts
Fixes #
- add `variantClass` prop to root element
- enhance examples
- add sizes example
- imporve `labelPosition` prop reactivity
> feat(steps): add root `variantClass` prop | enhance examples

- packages/oruga/src/components/table/TableMobileSort.vue
- add internal `addons` prop to mobile sort `field` component wrapper
> fix(table): add `addons` prop to mobile sort internal field component

- packages/oruga/src/components/upload/examples/base.vue
- packages/oruga/src/components/upload/examples/disabled.vue
- packages/oruga/src/components/upload/examples/drag-drop.vue
- packages/oruga/src/components/upload/examples/index.vue
- packages/oruga/src/components/upload/examples/variants.vue
- add upload variant examples
- add upload disabled examples
- add upload expanded examples
> docs(upload): enhance examples

- packages/oruga/src/components/autocomplete/Autocomplete.vue
- packages/oruga/src/components/carousel/Carousel.vue
- packages/oruga/src/components/datepicker/Datepicker.vue
- packages/oruga/src/components/datepicker/DatepickerMonth.vue
- packages/oruga/src/components/datepicker/DatepickerTableRow.vue
- packages/oruga/src/components/datepicker/examples/slots.vue
- packages/oruga/src/components/field/Field.vue
- packages/oruga/src/components/sidebar/Sidebar.vue
- packages/oruga/src/components/steps/StepItem.vue
- packages/oruga/src/components/steps/Steps.vue
- packages/oruga/src/components/steps/tests/StepsExample.vue
- packages/oruga/src/components/steps/tests/__snapshots__/steps.test.ts.snap
- packages/oruga/src/components/steps/tests/steps.axe.test.ts
- packages/oruga/src/components/steps/types.ts
- packages/oruga/src/components/table/Table.vue
- packages/oruga/src/components/table/TableColumn.vue
- packages/oruga/src/components/table/types.ts
- packages/oruga/src/components/tabs/TabItem.vue
- packages/oruga/src/components/tabs/Tabs.vue
- packages/oruga/src/components/tabs/types.ts
- packages/oruga/src/components/taginput/Taginput.vue
- packages/oruga/src/components/timepicker/Timepicker.vue
- packages/oruga/src/composables/defineClasses.ts
- check proper vue `effecScope` in `defineClasses`
- refactor class computation for some components to avoid unnecessary computation on change
> fix(performance): resolve a memory leak in `defineClasses` with wrong effectScope

- packages/oruga/src/components/steps/StepItem.vue
- packages/oruga/src/components/steps/tests/steps.integration.test.ts
- packages/oruga/src/components/tabs/TabItem.vue
- packages/oruga/src/components/tabs/tests/tabs.integration.test.ts
- add prop  `component`, `props`, `events` to StepItems and TabsItem
> feat(Tabs|Steps): add `component` prop to item

- packages/oruga/src/components/loading/Loading.vue
- packages/oruga/src/components/modal/Modal.vue
- add `scrollClipClass` and `noScrollClass` class to Loading component
> feat(loading): add body noScroll class when fullpage

- packages/oruga/src/components/autocomplete/Autocomplete.vue
- packages/oruga/src/components/autocomplete/examples/infinite-scroll.vue
- packages/oruga/src/components/autocomplete/props.ts
- packages/oruga/src/components/checkbox/Checkbox.vue
- packages/oruga/src/components/checkbox/props.ts
- packages/oruga/src/components/dropdown/Dropdown.vue
- packages/oruga/src/components/dropdown/DropdownItem.vue
- packages/oruga/src/components/dropdown/props.ts
- packages/oruga/src/components/dropdown/types.ts
- packages/oruga/src/components/radio/Radio.vue
- packages/oruga/src/components/radio/props.ts
- packages/oruga/src/components/select/Select.vue
- packages/oruga/src/components/select/props.ts
- packages/oruga/src/components/steps/StepItem.vue
- packages/oruga/src/components/steps/Steps.vue
- packages/oruga/src/components/steps/props.ts
- packages/oruga/src/components/steps/types.ts
- packages/oruga/src/components/switch/Switch.vue
- packages/oruga/src/components/switch/props.ts
- packages/oruga/src/components/tabs/TabItem.vue
- packages/oruga/src/components/tabs/Tabs.vue
- packages/oruga/src/components/tabs/props.ts
- packages/oruga/src/components/tabs/types.ts
- packages/oruga/src/components/taginput/Taginput.vue
- packages/oruga/src/components/taginput/props.ts
- packages/oruga/src/composables/useOptions.ts
- remove some type restrictions
> refactor: update generic types

- packages/oruga/src/components/autocomplete/tests/__snapshots__/autocomplete.test.ts.snap
- packages/oruga/src/components/datepicker/tests/__snapshots__/datepicker.test.ts.snap
- packages/oruga/src/components/datetimepicker/tests/__snapshots__/datetimepicker.test.ts.snap
- packages/oruga/src/components/dropdown/Dropdown.vue
- packages/oruga/src/components/dropdown/tests/__snapshots__/dropdown.integration.test.ts.snap
- packages/oruga/src/components/dropdown/tests/__snapshots__/dropdown.test.ts.snap
- packages/oruga/src/components/taginput/tests/__snapshots__/taginput.test.ts.snap
- packages/oruga/src/components/timepicker/tests/__snapshots__/timepicker.test.ts.snap
- add `toggle` prop to trigger slot
> feat(dropdown): add `toggle` prop to `trigger` slot

- packages/oruga/src/components/pagination/Pagination.vue
- packages/oruga/src/components/pagination/PaginationButton.vue
- packages/oruga/src/components/pagination/examples/inspector.vue
- packages/oruga/src/components/pagination/tests/__snapshots__/pagination.test.ts.snap
- packages/oruga/src/components/types.ts
- adjust class names to match other component class patterns
- update default classes
> feat(pagination): adjust class names to match other components class pattern

- packages/oruga/src/components/button/Button.vue
- packages/oruga/src/components/button/propts.ts
- packages/oruga/src/components/datepicker/examples/programmatically.vue
- packages/oruga/src/components/datepicker/examples/slots.vue
- packages/oruga/src/components/datepicker/examples/trigger.vue
- packages/oruga/src/components/datetimepicker/props.ts
- packages/oruga/src/components/dropdown/examples/programmatically.vue
- update button props api from runtime-approach to type-approach
- fix some example button wrong properties
> refactor(button): update props api

- packages/oruga/src/components/autocomplete/Autocomplete.vue
- packages/oruga/src/components/carousel/Carousel.vue
- packages/oruga/src/components/checkbox/Checkbox.vue
- packages/oruga/src/components/datepicker/Datepicker.vue
- packages/oruga/src/components/datetimepicker/Datetimepicker.vue
- packages/oruga/src/components/dropdown/examples/inspector.vue
- packages/oruga/src/components/field/Field.vue
- packages/oruga/src/components/field/fieldInjection.ts
- packages/oruga/src/components/input/Input.vue
- packages/oruga/src/components/loading/Loading.vue
- packages/oruga/src/components/loading/examples/programmatically.vue
- packages/oruga/src/components/menu/Menu.vue
- packages/oruga/src/components/menu/MenuItem.vue
- packages/oruga/src/components/modal/Modal.vue
- packages/oruga/src/components/notification/NotificationNotice.vue
- packages/oruga/src/components/radio/Radio.vue
- packages/oruga/src/components/select/Select.vue
- packages/oruga/src/components/sidebar/Sidebar.vue
- packages/oruga/src/components/slider/Slider.vue
- packages/oruga/src/components/steps/Steps.vue
- packages/oruga/src/components/switch/Switch.vue
- packages/oruga/src/components/table/Table.vue
- packages/oruga/src/components/tabs/Tabs.vue
- packages/oruga/src/components/taginput/Taginput.vue
- packages/oruga/src/components/timepicker/Timepicker.vue
- packages/oruga/src/components/tooltip/Tooltip.vue
- packages/oruga/src/components/upload/Upload.vue
- packages/oruga/src/components/utils/PickerWrapper.vue
- packages/oruga/src/composables/useInputHandler.ts
- packages/oruga/src/composables/useParentProvider.ts
- refactor old `ref(null)` to new `useTemplateRef("...")` composable syntax
> refactor: use useTemplateRef composable

- packages/oruga/src/components/autocomplete/tests/__snapshots__/autocomplete.test.ts.snap
- packages/oruga/src/components/datepicker/tests/__snapshots__/datepicker.test.ts.snap
- packages/oruga/src/components/datetimepicker/tests/__snapshots__/datetimepicker.test.ts.snap
- packages/oruga/src/components/input/Input.vue
- packages/oruga/src/components/input/tests/__snapshots__/input.test.ts.snap
- packages/oruga/src/components/taginput/tests/__snapshots__/taginput.test.ts.snap
- packages/oruga/src/components/timepicker/tests/__snapshots__/timepicker.test.ts.snap
- move the left icon html element before the html input element to get a better syntactic sugar
> feat(input): move the left icon element before the input element

- packages/oruga/vite.config.ts
- fix type generation, which got brocken after tsconfig update
> build: fix types generation

- packages/oruga/src/components/menu/MenuItem.vue
- packages/oruga/src/components/menu/examples/inspector.vue
- packages/oruga/src/components/menu/tests/__snapshots__/menu.integration.test.ts.snap
- packages/oruga/src/components/menu/tests/menu.integration.test.ts
-  refactor class names to match other components class name patterns
> feat(menu): refactor class names to match other components class name patterns

- packages/oruga/src/components/carousel/Carousel.vue
- packages/oruga/src/components/carousel/CarouselItem.vue
- packages/oruga/src/components/carousel/props.ts
- packages/oruga/src/components/collapse/Collapse.vue
- packages/oruga/src/components/collapse/props.ts
- packages/oruga/src/components/field/Field.vue
- packages/oruga/src/components/field/fieldInjection.ts
- packages/oruga/src/components/field/props.ts
- packages/oruga/src/components/menu/Menu.vue
- packages/oruga/src/components/menu/MenuItem.vue
- packages/oruga/src/components/menu/props.ts
- packages/oruga/src/components/modal/Modal.vue
- packages/oruga/src/components/modal/tests/__snapshots__/modal.test.ts.snap
- packages/oruga/src/components/pagination/Pagination.vue
- packages/oruga/src/components/pagination/examples/base.vue
- packages/oruga/src/components/pagination/props.ts
- packages/oruga/src/components/skeleton/Skeleton.vue
- packages/oruga/src/components/skeleton/props.ts
- packages/oruga/src/components/tooltip/Tooltip.vue
- packages/oruga/src/components/tooltip/props.ts
- update leftover components to type-based declaration approach
> refactor: update props to type-based declaration approach

- packages/oruga/src/components/datepicker/examples/inspector.vue
- packages/oruga/src/components/datetimepicker/examples/inspector.vue
- use `useOruga` composable in inspector examples
> docs: solve inspector issues

- packages/oruga/src/components/autocomplete/Autocomplete.vue
…button is clicked
Fixes #1149
- fix Autocomplete input content clearing when no option is selected (aka input is cleared)
> fix(autocomplete): solve input does not get cleared

- packages/oruga/src/components/loading/index.ts
- packages/oruga/src/components/loading/useLoadingProgrammatic.ts
- packages/oruga/src/components/modal/index.ts
- packages/oruga/src/components/modal/useModalProgrammatic.ts
- packages/oruga/src/components/notification/index.ts
- packages/oruga/src/components/notification/useNotificationProgrammatic.ts
- packages/oruga/src/components/programmatic/InstanceRegistry.ts
- packages/oruga/src/components/programmatic/ProgrammaticComponent.ts
- packages/oruga/src/components/programmatic/index.ts
- packages/oruga/src/components/programmatic/useProgrammatic.ts
- packages/oruga/src/components/sidebar/index.ts
- packages/oruga/src/components/sidebar/useSidebarProgrammatic.ts
- add a `count()` function to the programmatic interfaces, which counts the instances of this instance registry
> feat(programmatic): add programmatic instance `count()` function

- packages/oruga/src/components/notification/examples/programmatically.vue
> docs(notification): update programmatically example

- packages/oruga/src/components/skeleton/Skeleton.vue
- packages/oruga/src/components/skeleton/props.ts
- packages/oruga/src/components/types.ts
- rename skeleton classes to match name pattern
> feat(skeleton): rename classes to match pattern

- packages/oruga/src/components/taginput/Taginput.vue
- packages/oruga/src/components/taginput/examples/index.vue
- packages/oruga/src/components/taginput/examples/sizes.vue
- add variant class to Taginput root element
- move size class from container to Taginput root element
- add size examples
> feat(taginput): move variant and size class to root element

- packages/oruga/src/components/tooltip/Tooltip.vue
- packages/oruga/src/components/tooltip/props.ts
- packages/oruga/src/components/types.ts
- make `arrowVariantClass` class available
> fix(tooltip): make `arrowVariantClass` class available

- packages/docs/components/Switch.md
- packages/oruga/src/components/autocomplete/tests/__snapshots__/autocomplete.test.ts.snap
- packages/oruga/src/components/checkbox/Checkbox.vue
- packages/oruga/src/components/checkbox/props.ts
- packages/oruga/src/components/checkbox/tests/__snapshots__/checkbox.test.ts.snap
- packages/oruga/src/components/checkbox/tests/checkbox.test.ts
- packages/oruga/src/components/datepicker/tests/__snapshots__/datepicker.test.ts.snap
- packages/oruga/src/components/datetimepicker/tests/__snapshots__/datetimepicker.test.ts.snap
- packages/oruga/src/components/field/tests/field.test.ts
- packages/oruga/src/components/input/Input.vue
- packages/oruga/src/components/input/props.ts
- packages/oruga/src/components/input/tests/__snapshots__/input.test.ts.snap
- packages/oruga/src/components/input/tests/input.test.ts
- packages/oruga/src/components/radio/Radio.vue
- packages/oruga/src/components/radio/props.ts
- packages/oruga/src/components/radio/tests/__snapshots__/radio.test.ts.snap
- packages/oruga/src/components/select/Select.vue
- packages/oruga/src/components/select/props.ts
- packages/oruga/src/components/select/tests/__snapshots__/select.test.ts.snap
- packages/oruga/src/components/select/tests/select.test.ts
- packages/oruga/src/components/switch/Switch.vue
- packages/oruga/src/components/switch/examples/readme.md
- packages/oruga/src/components/switch/props.ts
- packages/oruga/src/components/switch/tests/__snapshots__/switch.test.ts.snap
- packages/oruga/src/components/switch/tests/switch.test.ts
- packages/oruga/src/components/taginput/tests/__snapshots__/taginput.test.ts.snap
- packages/oruga/src/components/timepicker/tests/__snapshots__/timepicker.test.ts.snap
- packages/oruga/src/components/types.ts
- Unify Input component classes
- Unify Select component classes
- Unify Switch component classes
- Unify Radio component classes
- Unify Checkbox component classes
> feat: unify HTML input based component classes

- packages/oruga/src/components/datepicker/Datepicker.vue
- packages/oruga/src/components/datepicker/DatepickerMonth.vue
- packages/oruga/src/components/datepicker/DatepickerTable.vue
- packages/oruga/src/components/datepicker/DatepickerTableRow.vue
- packages/oruga/src/components/datepicker/examples/inspector.vue
- packages/oruga/src/components/datepicker/props.ts
- packages/oruga/src/components/datepicker/tests/__snapshots__/datepicker.test.ts.snap
- packages/oruga/src/components/datepicker/tests/datepicker.test.ts
- packages/oruga/src/components/datetimepicker/tests/__snapshots__/datetimepicker.test.ts.snap
- packages/oruga/src/components/types.ts
- remove unnecessary classes and div wrapper
- use full component name as class name instead of an abbreviation
> feat(datepicker): unify class names & remove unnecessary classes

- package.json
- packages/examples/tsconfig.json
- packages/examples/vite.config.js
- packages/oruga/tsconfig.app.json
- Remove generated test types from build output of the examples and oruga package
- Add global build script to build all packages
> build: remove tests from build output

- packages/oruga/src/components/menu/Menu.vue
- packages/oruga/src/components/menu/MenuItem.vue
- packages/oruga/src/components/menu/examples/links.vue
- update event handler for Menu and MenuItem component
- clear focused element on focusout
> fix(menu): solve keyboard navigation issues

- packages/docs/.vitepress/theme/components/ExampleShowcase.ce.vue
- fix example-showcase component missing template
> docs: fix example-showcase component missing template

- packages/oruga/src/components/carousel/examples/autoplay.vue
- packages/oruga/src/components/carousel/examples/custom.vue
- packages/oruga/src/components/carousel/examples/index.vue
- packages/oruga/src/components/carousel/examples/indicators.vue
- packages/oruga/src/components/carousel/examples/list.vue
- update docs examples for carousel
> docs(carousel): add indicators example

- packages/oruga/src/components/steps/Steps.vue
- packages/oruga/src/components/steps/examples/base.vue
- packages/oruga/src/components/steps/examples/inspector.vue
- packages/oruga/src/components/steps/examples/sizes.vue
- packages/oruga/src/components/steps/examples/variants.vue
- packages/oruga/src/components/taginput/examples/sizes.vue
- The button disable state calculation included the `clickable' state steps, which was incorrect behaviour
> fix(steps): solve steps button navigation does not work properly

- packages/oruga/src/components/pagination/Pagination.vue
- packages/oruga/src/components/pagination/tests/__snapshots__/pagination.test.ts.snap
-  update pagination button default classes
> feat(pagination): update pagination button default classes

- package-lock.json
- packages/docs/package.json
- packages/examples/package.json
- packages/oruga/package.json
- packages/oruga/src/components/autocomplete/Autocomplete.vue
- packages/oruga/src/components/carousel/Carousel.vue
- packages/oruga/src/components/datepicker/Datepicker.vue
- packages/oruga/src/components/datetimepicker/Datetimepicker.vue
- packages/oruga/src/components/dropdown/Dropdown.vue
- packages/oruga/src/components/taginput/Taginput.vue
- packages/oruga/src/components/timepicker/Timepicker.vue
- packages/oruga/src/utils/config.ts
- packages/oruga/src/utils/helpers.ts
> chore: update dependencies

- packages/oruga/src/components/dropdown/Dropdown.vue
- packages/oruga/src/components/dropdown/DropdownItem.vue
- packages/oruga/src/components/dropdown/types.ts
- set focused item on mouse item enter equivalent to keyboard navigation
> fix(dropdown): set item focused on hover

- packages/docs/components/Table.md
- packages/oruga/src/components/table/Table.vue
- packages/oruga/src/components/table/TableColumn.vue
- packages/oruga/src/components/table/props.ts
- remove TableColumn prop `visible` because of duplication with `hidden`
> feat(table): remove TableColumn prop `visible`

- packages/oruga/src/components/pagination/Pagination.vue
- packages/oruga/src/components/pagination/PaginationButton.vue
- packages/oruga/src/components/pagination/tests/__snapshots__/pagination.test.ts.snap
- packages/oruga/src/components/pagination/tests/pagination.test.ts
Part of #672
- add pagination tests
> test(pagination): add pagination tests

- packages/oruga/src/components/programmatic/useProgrammatic.ts
- prevent inject key not found vue warn in dev mode
> fix(programmatic): prevent console warn in dev mode

- packages/oruga/src/components/programmatic/useProgrammatic.ts
- return the public component instance directly from the mounted component instead of the root from the app instance
> fix(programmatic): return exposed functionalities from programmatic component

- packages/oruga/src/components/autocomplete/Autocomplete.vue
- packages/oruga/src/components/autocomplete/examples/selection.vue
- packages/oruga/src/components/autocomplete/tests/autocomplete.test.ts
Fixes #1263
- update internal value handling for selected option and input value
- add tests
> fix(1263): solve autocomplete two-way-binding selection issues

- packages/oruga/src/composables/useTrapFocus.ts
- Increase focusable element query restriction for trapFocus elements
> feat: extend `trapFocus` focusable elements query

- packages/oruga/src/components/slider/Slider.vue
The normal slider is not clickable as it used to be prior to 0.9.x. Here's Oruga 0.8.12
https://github.com/user-attachments/assets/eb5bce6e-6922-4698-85a8-b630255b5e5c
and here's the current version
https://github.com/user-attachments/assets/20f54f34-7630-46aa-b440-85ce29add37b
However, the range version of the slider is unaffected by the bug. The root cause is the slider checks to confirm it can find all the template refs on the page on click, including the end thumb, which doesn't exist unless you're doing a range.
- Only checks for end thumb when in range mode
- Adds isRange computed to make things a little more DRY
> fix(slider): solve non-range slide is not clickable

- packages/oruga/src/composables/useTrapFocus.ts
- add preventScroll for trapFocus first focus
> fix(trapFocus): add preventScroll for trapFocus first focus

- packages/docs/documentation/customisation.md
- packages/docs/documentation/themes.md
Fixes #
- Navigate theme section links info box
- Referring line Steps comments section
> docs: update section links

- package-lock.json
- packages/oruga/src/composables/tests/useInputHandler.browser.test.ts
- packages/oruga/src/composables/useInputHandler.ts
- packages/oruga/src/types/config.ts
- `useInputHandler` now has browser tests for its constraint validation behavior.
- `useInputHandler` scrolls to invalid form controls even if they're outside an `<OField>`.
- Changes to constraint validation attributes correctly trigger validation message updates even when the input didn't previously require a `MutationObserver` to watch for attribute changes.
> test(input): test input handler

- packages/oruga/src/components/field/Field.vue
- correct field class with modifiers to have douple dash instead of one dash
> fix(field): correct default classes to fit BEM convention

- package-lock.json
- packages/docs/components/Autocomplete.md
- packages/docs/components/Breadcrumb.md
- packages/docs/components/Datepicker.md
- packages/docs/components/Dropdown.md
- packages/docs/components/Menu.md
- packages/docs/components/Modal.md
- packages/docs/components/Switch.md
- packages/docs/components/Table.md
- packages/docs/components/Tag.md
- packages/docs/components/Taginput.md
- packages/docs/package.json
- packages/docs/themes/theme-bulma.md
- packages/docs/themes/theme-oruga.md
- update theme packages dependencies
> docs: update theme dependencies

- packages/oruga/src/components/notification/index.ts
- add ONotificationNotice component export
> feat(notification): add ONotificationNotice component export

- packages/oruga/src/components/loading/Loading.vue
- packages/oruga/src/components/loading/tests/__snapshots__/loading.test.ts.snap
- packages/oruga/src/components/table/Table.vue
- packages/oruga/src/components/table/TableColumn.vue
- packages/oruga/src/components/table/props.ts
- packages/oruga/src/components/table/types.ts
- packages/oruga/src/types/utils.ts
- add `keyof T` to `DeepKeys<T>` type
- update `TableColumn<T>` type
> fix(table): let `keyof T` be a possible column field key

- packages/oruga/src/components/input/Input.vue
- packages/oruga/src/components/table/Table.vue
- packages/oruga/src/composables/useDebounce.ts
- packages/oruga/src/composables/useParentProvider.ts
- packages/oruga/src/composables/useScrollHelper.ts
- remove unused `immediate` arg from `useDebounce` composable
- update comments
- update `useDebounce` usage inside components
> refactor: cleanup `useDebounce` composable

- packages/oruga/src/components/steps/examples/vertical.vue
- add `variant` selection to Steps vertical example
> docs(steps): add variant to vertical example

- .github/workflows/gen-check.yml
- .scripts/gen-comp-types.ts
- .scripts/gen-volar-dts.ts
- .scripts/sync-version.ts
- packages/docs/src/utils.ts
- packages/oruga/components.d.ts
- packages/oruga/volar.d.ts
- add typings in gen scripts
- add component ordering for a consistent order
- remove git add from gen-check workflow
> chore: fix file generation
