packages/oruga/src/components/autocomplete/Autocomplete.vue, packages/oruga/src/scss/components/_autocomplete.scss
This allows the input to be styled differently depending on the direction of the dropdown. Ex: input border radius can adjust depending on if the dropdown is showing above or below the input.
=> Move `openedTopClass` to `rootClasses()`

packages/docs/components/Table.md
=> fix(table): typo in sandbox docs

packages/oruga-next/src/utils/CheckRadioMixin.ts
Fixes #83 
- Make Radio buttons emit `update:modelValue` instead of `input` event in oruga-next
=> Emit update:modelValue instead of input

packages/docs/components/Select.md
This PR adds `selectClass` prop to the **Select** component section in the docs, looks like it was missing. 
If I overlooked something, please feel free to ignore this PR.
=> Select class prop in docs

packages/docs/documentation/README.md
Just two simple typo fixes in the docs :)
=> fix typos in docs

.github/CONTRIBUTING.md
Corrected a typo in `CONTRIBUTING.md` where the main branch `develop` was named `dev`.
=> fix branch name in CONTRIBUTING.md

packages/oruga/src/scss/components/_tabs.scss
Fixes #
Fixes #112 
- add `overflow-x: auto`
- add `padding-bottom: $tabs-border-bottom-width` to keep showing the border-bottom
- hide the scrollbar
=> add scroll-x in _tabs.scss

packages/oruga-next/src/components/table/Table.vue
This just adds one value to the emits array to stop the vue warning message.
[Vue warn]: Component emitted event "cell-click" but it is neither declared in the emits option nor as an "onCell-click" prop.
Fixes #
- Add 'cell-click' value to array 'emits'
=> Update Table.vue to remove Vue warn message

packages/oruga-next/src/components/input/Input.vue
Fixes #127 
- Rename `rrightIconClick` to `rightIconClick`
=> Fix typo in rightIconClick event

packages/oruga-next/src/components/table/Table.vue
When running oruga-next with compat mode in Vue3, it's showing me warnings in the console. See the link they provide along the warnings: https://v3.vuejs.org/guide/migration/watch.html
I had problems with auto-formatting in VSCode, it was changing the whole file. Unfortunately the editorconfig may be missing some settings. But I'm not very confident with the setting up formatters in general. :-/
=> deep watch arrays in Table component

packages/oruga-next/src/components/table/TableMobileSort.vue
Fixes an error that occurs when using oruga-next alone: it tries to load a helper funcion (`getValueByPath`) from the oruga package.
=> Fix the path to load helper in `OTableMobileSort` (oruga-next)

packages/docs/documentation/README.md, packages/oruga-next/src/utils/BaseComponentMixin.ts, packages/oruga-next/src/utils/config.ts, packages/oruga/src/utils/BaseComponentMixin.js, packages/oruga/src/utils/BaseComponentMixin.spec.js
Fixes #184 
In case you want to transform applied classes' names you can use `transformClasses` function directly in your configuration.
```js
Vue.use(Config, {
button: {
transformClasses: (appliedClasses) => {
return appliedClasses.replace(/-/g, '--')
}
}
...
})
```
You can also use `transformClasses` globally if you need to transform classes for any component.
```js
Vue.use(Config, {
transformClasses: (appliedClasses) => {
return appliedClasses.replace(/-/g, '--')
}
...
})
```
=> feat: add transformClasses functionality

packages/docs/documentation/README.md, packages/oruga-next/src/utils/BaseComponentMixin.ts, packages/oruga/src/utils/BaseComponentMixin.js, packages/oruga/src/utils/BaseComponentMixin.spec.js
`override` property now replaces Oruga existing classes completely, ignoring configuration.
=> Override prop behaviour 

packages/oruga-next/src/components/field/FieldBody.vue
Fixes #226 
render `VNodes` of type `Comment` or `Text` as they are and do not wrap them in `OField`
-
-
-
=> fix: rendering of comments in horizontal fields

packages/oruga-next/src/components/datepicker/Datepicker.vue
This change prevents the warnings when opening/closing the datepicker
=> fix: missing 'active-change' event in Datepicker emits

packages/oruga/src/components/loading/index.js
This change makes programmatic loading component consistent with modal and notification components. It is needed as correct parent context may be necessary if a custom icon component is defined.
=> fix: add missing parent param to programmatic loading component

packages/oruga-next/src/utils/TabbedMixin.ts, packages/oruga/src/utils/TabbedMixin.js
Fixes #241 
- `oldTab` in `performAction()` always was the `activeItem`, so the index was always the same in `deactivate()`/`activate()` and therefor transistion name always `slide-prev`
- `performAction()` was always called 4 times (2x `childClick()`, 2x `modelValue()`-watcher
=> fix: set tabbed transitions correctly

packages/oruga-next/src/components/autocomplete/Autocomplete.vue
Fixes #240
uses `if(!this.$refs.dropdown)` instead.
=> Fixes #240 by checking valid $refs.dropwdown

packages/oruga-next/src/utils/FormElementMixin.ts
This PR fixes a null pointer exception: 
```
FormElementMixin-6fb41465.js:167 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'checkValidity')
at Proxy.checkHtml5Validity (FormElementMixin-6fb41465.js:167)
at Proxy.<anonymous> (Autocomplete-aa443bda.js:614)
```
I have also fixed other errors in this file by searching for `=== undefined`
- change all `x === undefined` to `!x`
=> Fixes more null errors

packages/oruga-next/src/components/carousel/Carousel.vue, packages/oruga/src/components/carousel/Carousel.vue
Fixes #264 
- Check `event` in Carousel dragEnd method before using it
=> fix(carousel): check event in dragEnd #264

packages/oruga-next/package.json, packages/oruga-next/rollup.config.js
This PR (which will be a breaking change) changes the file extension for esm builds to `.mjs` to enable native node esm imports (for frameworks like nuxt 3).
=> build: use `.mjs` extension for built esm files

packages/oruga-next/src/components/autocomplete/Autocomplete.spec.js, packages/oruga-next/src/components/autocomplete/Autocomplete.vue, packages/oruga-next/src/components/dropdown/Dropdown.spec.js, packages/oruga-next/src/components/dropdown/Dropdown.vue, packages/oruga/src/components/autocomplete/Autocomplete.spec.js, packages/oruga/src/components/autocomplete/Autocomplete.vue, packages/oruga/src/components/dropdown/Dropdown.spec.js, packages/oruga/src/components/dropdown/Dropdown.vue
- Add a `menuTag` property to the Dropdown component. It'll help me use Oruga with DaisyUI which require the dropdown to be a li
- Add a `menuTag` and `itemTag` to the Autocomplete component, for the very same reason
I need some guidante to write tests on this
=> [rfc] chore(dropdown): Add a property to configure dropdown/autocomplete menu tag

packages/docs/components/Modal.md, packages/oruga-next/src/components/modal/Modal.vue, packages/oruga-next/src/components/modal/index.ts, packages/oruga/src/components/modal/Modal.vue, packages/oruga/src/components/modal/examples/Modal.md, packages/oruga/src/components/modal/index.js
Proposal for #225
Depends on PR #315 
- Modal instance now has a "promise" property that when using $oruga.modal.open contains a promise that will resolve to the value passed to the $emit('close', value)
- when a modal is canceled, the promise resolves {action: 'cancel', method: 'x'}
=> add a promise return to the programmatic modal open.

packages/oruga-next/src/components/carousel/Carousel.vue, packages/oruga-next/src/utils/NoticeMixin.ts, packages/oruga/src/components/carousel/Carousel.vue, packages/oruga/src/utils/NoticeMixin.js
Fixes default property functions that were not returning any value.
One example is the default "duration" for notifications to be undefined and thus causing notifications to  immediately dismiss.
=> Fix default property value functions

packages/docs-next/documentation/index.md
- changes link in documentation/index.md to reference `#base-style` instead of `documentation/#base-style`.
Without this vitepress yelps that the there is a dead link
=> Correct bad link in index.md that caused vitepress to complain about a dead link

README.md, packages/docs-next/documentation/index.md, packages/docs/documentation/README.md, packages/oruga-next/src/components/index.ts, packages/oruga-next/src/components/plugins.ts, packages/oruga-next/src/index.ts, packages/oruga/src/components/index.js, packages/oruga/src/components/plugins.js, packages/oruga/src/index.js
It allows components to be registered locally instead of globally (see [1]).
Some IDE can automatically insert these imports which greatly reduces the hassle
of using tree shaking.
It doesn't handle CSS imports yet, but the old implementation did not either.
A promising solution is to use a bundler plugin, which is adopted by Element
Plus [2].
I'm keeping the old, plugin based API for backward compatibility. Eventually
we can remove it in favor of direct imports.
[1]: https://vuejs.org/guide/components/registration.html#local-registration
[2]: https://github.com/element-plus/unplugin-element-plus
=> feat(oruga, oruga-next): Export individual components

packages/oruga/src/scss/components/_checkbox.scss, packages/oruga/src/scss/components/_radio.scss
Fixes https://github.com/oruga-ui/oruga/issues/415
- replace "color-adjust" by "print-color-adjust"  in `oruga` module
---
tests pass successfully locally 
```
#~  npm run test:oruga
> test:oruga
> lerna run test --scope @oruga-ui/oruga
lerna notice cli v3.22.1
lerna notice filter including "@oruga-ui/oruga"
lerna info filter [ '@oruga-ui/oruga' ]
lerna info Executing command in 1 package: "npm run test"
lerna info run Ran npm script 'test' in '@oruga-ui/oruga' in 21.7s:
> @oruga-ui/oruga@0.5.6 test
> npm run lint && npm run unit
> @oruga-ui/oruga@0.5.6 lint
> eslint --ext .js,.vue src
/home/emeric/Projets/oruga/packages/oruga/src/components/table/TableColumn.vue
56:13  warning  Keys starting with with '_' are reserved in '_isTableColumn' group  vue/no-reserved-keys
✖ 1 problem (0 errors, …
```
=> fix warning by replacing "color-adjust" by "print-color-adjust"

packages/oruga-next/src/utils/MatchMediaMixin.ts, packages/oruga/src/utils/MatchMediaMixin.js
Handle `window.matchMedia` being undefined properly. This can happen when it's hard to mock environment (jest/jsdom) like done in d0262fd675f51d5262737ec1ec3fc0f481db776b.
This should be harmless.
=> Handle non existing window.matchMedia

packages/docs/components/Steps.md, packages/oruga/src/components/steps/examples/Steps.md
When I created #422, I did not realize I was editing a generated file (`packages/docs/components/Steps.md`). This PR adds that code to the source file (`packages/oruga/src/components/steps/examples/Steps.md`).
As far as I can tell, I updated the `oruga-next` docs correctly in #422. But can you confirm that for me?
=> Fix Steps docs

packages/docs-next/.vitepress/theme/examples/field/inspector.vue, packages/docs/components/Field.md, packages/oruga-next/src/components/field/Field.spec.js, packages/oruga-next/src/components/field/Field.vue, packages/oruga/src/components/field/Field.spec.js, packages/oruga/src/components/field/Field.vue, packages/oruga/src/components/field/Inspector.vue, packages/oruga/src/components/field/__snapshots__/Field.spec.js.snap, packages/oruga/src/scss/components/_field.scss
Fixes #427 
- Keep `message` slot when component has `horizontal` props.
- Refactor `Field` component to avoid code duplication.
- Fix input spacing on mobile.
Before:
After:
=> Fixes message slot in OField component when horizontal

packages/oruga-next/src/components/modal/Modal.vue
Fixes #333
In `oruga-next`, the `close` event was being sent twice. Both `this.$emit('close')` and `this.onClose.apply(null, arguments)` send the `close` event. We can delete either of those statements to get a single `close` event to fire. I chose to delete `this.$emit('close')` because it wasn't sending arguments.
This double `close` event behavior does not seem to happen in `oruga`, so I did not make any changes there.
=> Fix modal calling onClose twice

packages/oruga-next/src/components/select/Select.vue, packages/oruga/src/components/select/Select.vue
Passes `autocomplete` prop through to `<OSelect>` like we would for other form elements.
=> fix(select): pass autocomplete prop through

packages/docs-next/documentation/index.md, packages/docs/documentation/README.md
Fixes #468 
-  `oruga/dist/` and `oruga-next/dist/` are the wrong paths, and the correct paths should be `@oruga-ui/oruga/dist/` and `@oruga-ui/oruga-next/dist/`
=> fix cdn link typo

packages/oruga/src/scss/components/_checkbox.scss
Fixes #
- change CSS rule on `o-chk__check`, from:
`@include avariable('background', 'checkbox-background-color', $checkbox-background-color);` 
to 
`@include avariable('background-color', 'checkbox-background-color', $checkbox-background-color);`
Right now we are using the `background` shorthand  to set a background color on ourga checkbox:
This will override any other settings made in background rule (like background-position, backgrouns-size, etc) and previously set on the same class
This property should be `background-color` instead:
=> fix: changed background for background-color on .o-chk_check

README.md
The Setup -> Vue 3 code example in README.md imports ```import Vue from 'vue``` instead of createApp. This is most probably a copy/paste mistake.
=> Fix wrong import for Vue3 example in README.md

packages/oruga/src/scss/components/_button.scss
Fixes #
- [Fixes #505](https://github.com/oruga-ui/oruga/issues/505)
- Change the variable `button-border-radius` to `button-rounded-border-radius` for rounded button.
=> fix: button-rounded-border-radius variable

packages/docs-next/components/Table.md, packages/docs/components/Table.md, packages/oruga-next/src/components/table/Table.vue, packages/oruga/src/components/table/Table.vue
This PR adds a slot named `preheader` inside `<thead>` in Table.vue, and mentions it in the documentation.
I see that there is a similar subheading slot feature for `OTableColumn` that is undocumented.  I found it while reading the code, and while I think it's interesting, I believe that the implementation is overly restrictive and overly complicated, so I didn't choose to follow that pattern here.
If a `Table.vue` user has a use case for extra table headers above or below the standard header, I think it's best to hand over full control rather than trying to introduce a limited API like the subheading pattern attempts to do.  For example, I need to add an extra header with `colspan` and special CSS.  The subheading pattern doesn't use `thAttrs`, so it's too restrictive for me. 
IMO the …
=> Adds slot preheader in Table.vue

packages/oruga-next/package.json
Resolves https://github.com/nuxt/nuxt/issues/20627
This adds subpath exports for imports from `@oruga-ui/oruga-next` that work in native Node ESM. (The `module` field is ignored by Node and without this change we will always import the CJS build when `@oruga-ui/oruga-next` is externalized.)
=> fix(oruga-next): provide node subpath exports

packages/oruga-next/src/components/input/Input.vue
Fixes #526
Fixes #527
This fixes `o-input` with `type=number` (see the linked issues).
Vue doesn't support `modelModifiers` fallthrough to native inputs (see https://github.com/vuejs/core/issues/1825) but simply converting the code to use `v-model` in `o-input` achieves the desired behaviour **and** makes it more consistent with native input.
Besides, the code becomes cleaner. I mean, why introducing a settable computable and not use?
=> better support o-input with input type=number

packages/oruga/src/scss/components/_table.scss
- fix typo in scss components file
- ⚠️ didn't generate new doc
=> fix: typo _table.scss 

packages/oruga-next/src/components/autocomplete/Autocomplete.vue
I have made some changes that address the following issues:
1) Missing events in the `emits` array
2) Not triggering `select-footer` event
Please note that I have only tested these changes manually. If you would like me to incorporate any modifications into the automatic tests, please let me know.
Additionally, this is only applicable to the `oruga-next` package. The `oruga` package looks fine to me: https://github.com/oruga-ui/oruga/blob/develop/packages/oruga/src/components/autocomplete/Autocomplete.vue#L568
=> [Autocomplete] Fix issue related to select-header and select-footer events

packages/oruga-next/src/components/autocomplete/Autocomplete.vue, packages/oruga-next/src/components/button/Button.vue, packages/oruga-next/src/components/dropdown/Dropdown.vue, packages/oruga-next/src/components/dropdown/DropdownItem.vue, packages/oruga-next/src/components/menu/MenuItem.vue, packages/oruga-next/src/components/pagination/PaginationButton.vue, packages/oruga-next/src/components/tabs/TabItem.vue, packages/oruga-next/src/utils/SlotComponent.ts
Fixes warnings in #502
- Adds `Component` to the types of all tag props, allowing actual components to be given as tag props, in addition to component names.
=> Add components to tag prop types

package-lock.json, packages/oruga-next/src/utils/MatchMediaMixin.ts, packages/oruga/src/utils/MatchMediaMixin.js
Fixes #566
Proposed Changes
- Call correct method for clean up
- Replace lifecycle hooks with browser executed ones
- Store MediaQueryList as a non-reactive reference
- Replace addListener as it's [depricated](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener)
=> Fix memory leak in MatchMediaMixin

packages/oruga-next/src/components/autocomplete/Autocomplete.vue
Fixes #552
Use `component` for the autocomplete items because it has a `is` property.
-
-
-
=> fix(autocomplete): use component

packages/oruga-next/src/components/datepicker/DatepickerTable.vue, packages/oruga-next/src/components/datepicker/DatepickerTableRow.vue
Fixed datepicker infinity loop.
Fixes #624 
- fix `changeFocus` method
- refactor focusedDate to prod binding
=> fix(datepicker): infinity loop

packages/docs-next/.vitepress/theme/examples/input/base.vue, packages/docs-next/components/Checkbox.md, packages/docs-next/components/Input.md, packages/docs-next/components/Radio.md, packages/docs-next/components/Switch.md, packages/oruga-next/src/components/checkbox/Checkbox.vue, packages/oruga-next/src/components/input/Input.vue, packages/oruga-next/src/components/radio/Radio.vue, packages/oruga-next/src/components/switch/Switch.vue
I added an `@input` event for all input to provide access to the native input event.
=> feat(inputs): add @input event

CHANGELOG.md
https://github.com/oruga-ui/oruga/blob/04d5cfbafa1c3b23fd5fda610eb947fd0a32f6dd/packages/oruga-next/src/components/collapse/Collapse.vue#L31C5-L31C14
Fixes #
-
-
-
=> docs(CHANGELOG.md): fix rename props ariaId to contentId

packages/docs-next/documentation/index.md
Fixes #
none
- .min.js file is missing from the previous link https://unpkg.com/@oruga-ui/oruga-next/dist/oruga.min.js
=> fix(docs): update oruga-next cdn link

packages/oruga-next/src/components/table/Table.vue
Non-extensible objects (such as VueJS computed properties) don't allow to be extended with Object.assign(). By inverting the two parameters, we copy all the properties of the row to the new `{ __rowKey: uuid() }` object instead.
Fixes `TypeError: can't define property "__rowKey": Object is not extensible`
=> fix(table): reorder params from Object.assign to allow for non-extensible objects

packages/docs-next/documentation/index.md
- add vue 2 deprecation warning
- update get started section
=> docs: update get-started

packages/oruga-next/src/components/table/Table.vue
Fixes https://github.com/oruga-ui/oruga/issues/712
=> fix(table): passive mode in current page binding

packages/oruga-next/src/types/config.ts, packages/oruga-next/src/utils/icons.ts
The `customIconPacks` options property has the wrong type definition.
=> fix(types): fix customIconPacks config

packages/oruga-next/src/components/autocomplete/Autocomplete.vue
Fixes #704
- Change autocomplete internal input v-bind / v-model prop order
=> fix(autocomplete): change input vbind vmodel prop order

packages/docs-next/documentation/customisation.md
v0.8 changes the Config interface
Fixes https://github.com/oruga-ui/oruga/issues/705
Thanks to @121593
- Remove menu-class config that disappeared from the Autocomplete component
- Change Config references to ConfigProgrammatic
- Enhance prgammatic usage docs section
=> docs: update customisation guidelines

packages/oruga-next/src/components/tooltip/Tooltip.vue
- stop position being outputted to console.log when tooltip is used
=> fix(tooltip): remove console.log usage in Tooltip component

packages/oruga-next/src/components/autocomplete/Autocomplete.vue
Fixes #718
Fixes #719
- remove autocomplete prop field default value
- do not hide autocomplete dropdown when no data if an empty slot is defined
=> fix(autocomplete) fix empty slot display and formatter prop usage

packages/oruga-next/src/components/taginput/Taginput.vue
I noticed you can't set a placeholder on the input item from the TagInput component
=> pass missing placeholder and validationMessage props to autocomplete component 

packages/docs-next/documentation/customisation.md, packages/oruga-next/src/composables/useComputedClass.ts, packages/oruga-next/src/types/config.ts, packages/oruga-next/src/utils/helpers.ts
Using the composition api, the `$data` and `$computed` attributes are no longer available on a component instance. 
Therefore they can't be used for the second parameter of the `ClassFunction` theme config. 
Since the ComponentContext then only contains the component props, I pass the props directly as the second parameter of the function. 
- update ComponentContext to ComponentProps
=> fix: update config ClassFunction second parameter from context to props

packages/oruga-next/src/components/taginput/Taginput.vue
- Change `v-if` to `v-show` to only hide an not remove the autocomplete input inside the taginput component
=> fix(taginput): only hide autocomplete input instead of unmount

packages/oruga-next/src/components/taginput/Taginput.vue
Otherwise it does pretty much nothing apart from allowing to use the `expandedClass`.
| Before | After |
|--------|--------|
| ![image](https://github.com/oruga-ui/oruga/assets/2197836/992d4913-3ea9-4e52-b118-766c7154880a) | ![image](https://github.com/oruga-ui/oruga/assets/2197836/3642db5c-e2b0-438e-b139-ad02c4b608bb) |
(when expanded has been hardcoded in the example in question)
=> fix(taginput): forward expanded prop to Autocomplete component so that it's passed to dropdown

packages/oruga-next/src/components/datepicker/Datepicker.vue, packages/oruga-next/src/components/datepicker/DatepickerMonth.vue, packages/oruga-next/src/components/datepicker/DatepickerTable.vue, packages/oruga-next/src/components/datepicker/DatepickerTableRow.vue, packages/oruga-next/src/components/datepicker/index.ts, packages/oruga-next/src/components/datepicker/types.ts, packages/oruga-next/src/components/datepicker/useDatepickerMixin.ts, packages/oruga-next/src/components/datepicker/useDatepickerMixins.ts, packages/oruga-next/src/components/datepicker/utils.ts, packages/oruga-next/src/components/datetimepicker/Datetimepicker.vue, packages/oruga-next/src/components/timepicker/Timepicker.vue, packages/oruga-next/src/components/timepicker/types.ts, packages/oruga-next/src/components/timepicker/useTimepickerMixins.ts
Fixes #780
- fix datepicker vue internal issue
- refactor useVModel composable to defineModel macro
- refactor datepicker utils
=> fix(datepicker): refactor datepicker related components

packages/oruga-next/src/components/autocomplete/Autocomplete.vue
This fixes an issue encountered while testing https://github.com/oruga-ui/oruga/pull/777 where the autocomplete does not display the contents of the empty slot when there are no results.
=> fix(autocomplete): show empty slot available

packages/oruga-next/src/composables/useScrollingParent.ts
Fixes #742
- add `isDefined` check for `nextParent` in `getScrollingParent` composable
=> fix(composable): prevent scrolling parent error with parent null

packages/oruga-next/src/components/autocomplete/Autocomplete.vue, packages/oruga-next/src/components/checkbox/Checkbox.vue, packages/oruga-next/src/components/datepicker/Datepicker.vue, packages/oruga-next/src/components/datetimepicker/Datetimepicker.vue, packages/oruga-next/src/components/dropdown/Dropdown.vue, packages/oruga-next/src/components/input/Input.vue, packages/oruga-next/src/components/loading/Loading.vue, packages/oruga-next/src/components/modal/Modal.vue, packages/oruga-next/src/components/notification/NotificationNotice.vue, packages/oruga-next/src/components/pagination/Pagination.vue, packages/oruga-next/src/components/radio/Radio.vue, packages/oruga-next/src/components/select/Select.vue, packages/oruga-next/src/components/sidebar/Sidebar.vue, packages/oruga-next/src/components/switch/Switch.vue, packages/oruga-next/src/components/taginput/Taginput.vue, packages/oruga-next/src/components/timepicker/Timepicker.vue, packages/oruga-next/src/components/upload/Upload.vue, packages/oruga-next/src/components/utils/PickerWrapper.vue, packages/oruga-next/src/composables/useInputHandler.ts
This makes it easier to programmatically focus an input component.
- expose `setFocus` for all input components
=> feat(inputs): expose setFocus function for all input components

packages/oruga-next/src/components/input/Input.vue
Fixes an issue encountered while testing https://github.com/oruga-ui/oruga/pull/777 where if the password reveal prop was set the password would not be hidden when the component initially loaded. Subsequently clicking the show/hide icon would work correctly.
=> fix(input): update password reveal 

packages/oruga/src/components/modal/Modal.vue
Part of #826
- make modal prop width reactive
=> fix(modal): make property `width` reactive

packages/oruga/src/types/programmatic.ts
Fixes #827
- adjus ProgrammaticExpose type
=> fix(programmatic): fix ProgrammaticExpose type

packages/oruga/src/composables/defineClasses.ts, packages/oruga/src/utils/helpers.ts
Fixes #823
- remove `unref` from `isDefined` helper
- add value really change check for `defineClasses` watcher
=> fix(helper): remove unintended unref function

packages/oruga/src/components/table/Table.vue
Fixes an issue where the table will display `stickyHeaderClass` when no value is provided for `props.stickyHeader`. 
- Cast `props.stickyHeader` to bool in `tableWrapperClasses`
=> fix(table): `stickyHeaderClass` should not display by default

packages/oruga/src/components/table/Table.vue, packages/oruga/src/components/types.ts
Oruga's table is deeply configurable, but with so many options it can be hard for devs to know which combination of options is the standard for a given application. This PR adds config support for a few table props related the visual presentation of the table. This will make it easier to set the visual standard for your app.
- Adds config support for `bordered`, `striped`, `narrowed` and `hoverable` table props, along with related types.
=> feat(table): make `bordered`, `striped`, `narrowed` and `hoverable` configurable

packages/docs/components/Table.md, packages/oruga/src/components/table/Table.vue, packages/oruga/src/components/table/TableColumn.vue, packages/oruga/src/components/table/types.ts
Fixes #838
- call toRow for props to prevent produce "Maximum recursive updates exceeded" when functions are given
=> fix(table): prevent TableColumn function props trigger recursive reactivity

packages/oruga/src/components/carousel/Carousel.vue, packages/oruga/src/components/carousel/CarouselItem.vue, packages/oruga/src/components/carousel/types.ts, packages/oruga/src/components/dropdown/DropdownItem.vue, packages/oruga/src/components/menu/Menu.vue, packages/oruga/src/components/menu/MenuItem.vue, packages/oruga/src/components/menu/types.ts, packages/oruga/src/components/slider/SliderTick.vue, packages/oruga/src/components/steps/StepItem.vue, packages/oruga/src/components/table/Table.vue, packages/oruga/src/components/tabs/TabItem.vue, packages/oruga/src/composables/useParentProvider.ts
- refactor the `useParentProvider` composable to always use computed refs as options data
- refactor types used for `useProviderParent` and `useProviderChild`
=> refactor: enhance `useParentProvider` composable type support

packages/oruga/src/components/steps/StepItem.vue, packages/oruga/src/components/tabs/TabItem.vue
Fixes #863
Replace `disabled` by `css`, the prop to disable transition is `css` https://vuejs.org/api/built-in-components.html#transition
=> fix(tabs): fix disable animation

packages/oruga/src/components/steps/StepItem.vue, packages/oruga/src/components/tabs/TabItem.vue
Found by #876 
- remove `toRaw` from computed provided item data to make the props reactive again
=> fix(step|tab): make item props reactive again

packages/oruga/src/components/table/TableColumn.vue
Part of #876 (no solved in detail)
- make table-column props reactive again (beside tdAttrs/thAttrs)
- deprecate tdAttrs/thAttrs on table-column (will be moved to table)
=> fix(table): make `TableColumn` props reactive again

packages/docs/.vitepress/theme/examples/taginput/custom-selected.vue, packages/oruga/src/components/taginput/Taginput.vue
Fixes #887
- Adds `removeItem` to `defineExpose` in `Taginput.vue` so that custom items can call it in their click event to remove the item.
=> feat(taginput): add removeItem as selected slot property (#887)

packages/oruga/src/components/menu/Menu.vue, packages/oruga/src/composables/useParentProvider.ts
Fixes #885
- add `UnwrapNestedRefs` type wrapper for `childItems` in `useProviderParent` composable
=> fix(menu): fix `useProviderParent` composable `childItems` type problem

packages/oruga/src/components/datepicker/Datepicker.vue, packages/oruga/src/components/datepicker/tests/datepicker.test.ts
Fixes #881
- Accept plain dates in `onChange`, not just date-range pairs
Note that parsing of date ranges is still broken; it collapses them to a single date.
That seems like a separate bug, though.
=> fix(datepicker): make date parsing work again

packages/oruga/src/components/table/Table.vue
Fixes table filtering when table is not yet sorted
`currentSortColumn` is undefined when the table is not sorted ( no `defaultSort` prop defined) and the property is accessed in `handleFilter` function throwing an error
Adding a safe guard in the function
=> fix(table): fix filtering when table is not sorted

packages/oruga/src/components/utils/PickerWrapper.vue
HTML constraint validation can apply even if we're not using the native date picker, so I don't see a strong reason to skip `checkHtml5Validity()`.
Previously, date and time pickers would only try to clear their constraint validation messages on direct user updates or `blur` events when in desktop mode, not on programmatic updates. In the video below, note that I have to blur the field before the validation message fixes itself:
[before.webm](https://github.com/oruga-ui/oruga/assets/2198455/dc545cc8-e21e-4e3f-8c48-9f2c9c1251fc)
This is inconsistent with the behavior of other inputs, which will clear their validation messages even if not updated due to direct user input.
[after.webm](https://github.com/oruga-ui/oruga/assets/2198455/9a65d1b3-15af-4553-ae0f-699a894ebefe)
Here's the code I …
=> fix: always validate programmatic date updates for picker components

packages/oruga/src/composables/useInputHandler.ts
When attributes related to HTML constraint validation change on an input, they may change or even remove the validation error on the input. Ideally, we'd reflect the change of validation error in the enclosing field.
Changes to the following attributes on an invalid form element should trigger a call to `checkHtml5Validity`:
- `required`
- `pattern`
- `maxlength`
- `minlength`
- `max`
- `min`
- `step`
Additionally, changes to the `disabled` attribute on the input or any ancestor `<fieldset>` should trigger a call to `checkHtml5Validity`.
```vue
<script setup lang="ts">
import { OCheckbox, OInput } from '@oruga-ui/oruga-next';
import { ref } from 'vue';
const val = ref("");
const required = ref(true);
const disabled = ref(false);
const groupDisabled = ref(false);
</script>
<template> …
```
=> feat(inputs): detect constraint validation attribute changes

packages/oruga/src/components/taginput/Taginput.vue
Fixes #925
- Create a new array instead of manipulating the existing one when adding or removing items
=> fix(taginput): solve defineModel macro array constrains

packages/oruga/src/components/table/Table.vue
=> fix(table): solve searchable filter bug

packages/oruga/src/components/autocomplete/Autocomplete.vue, packages/oruga/src/components/checkbox/Checkbox.vue, packages/oruga/src/components/datepicker/Datepicker.vue, packages/oruga/src/components/datetimepicker/Datetimepicker.vue, packages/oruga/src/components/input/Input.vue, packages/oruga/src/components/radio/Radio.vue, packages/oruga/src/components/select/Select.vue, packages/oruga/src/components/slider/Slider.vue, packages/oruga/src/components/switch/Switch.vue, packages/oruga/src/components/taginput/Taginput.vue, packages/oruga/src/components/timepicker/Timepicker.vue, packages/oruga/src/components/upload/Upload.vue, packages/oruga/src/composables/useInputHandler.ts
- expose the `modelValue` as `value` for every HTML input based component
=> feat: expose value for every HTML input based component

packages/oruga/src/composables/defineClasses.ts
Fixes #837
Fixes #853
- Adding a watcher for the class properties of a component to recompute the effective classes when the prop change
=> feat(reactivity): add component class props reactivity

packages/oruga/src/components/autocomplete/Autocomplete.vue, packages/oruga/src/components/dropdown/Dropdown.vue, packages/oruga/src/components/input/Input.vue, packages/oruga/src/components/select/examples/grouped.vue, packages/oruga/src/components/switch/Switch.vue, packages/oruga/src/components/switch/tests/switch.test.ts, packages/oruga/src/components/taginput/Taginput.vue, packages/oruga/src/composables/index.ts, packages/oruga/src/composables/useVModel.ts
Part of #994
- readd a simplified `useVModel` composable
- revert `defineModel` with `useVModel` for specific two-way-binded propertes with generics where the type is `T | T[]`
- fix some props
=> revert(defineModel): reuse `useVModel` composable for generics where the type is `T | T[]`

packages/oruga/src/components/autocomplete/Autocomplete.vue, packages/oruga/src/components/checkbox/Checkbox.vue, packages/oruga/src/components/field/Field.vue, packages/oruga/src/components/field/fieldInjection.ts, packages/oruga/src/components/input/Input.vue, packages/oruga/src/components/radio/Radio.vue, packages/oruga/src/components/select/Select.vue, packages/oruga/src/components/switch/Switch.vue, packages/oruga/src/components/upload/Upload.vue, packages/oruga/src/components/utils/PickerWrapper.vue
Fixes #935
- Improve a11y by:
- Add a unique ID to the field message `p` element.
- Make the attributes defined by the field available for inputs.
- Bind the attributes defined by the field to the input element.
=> feat(field): programmatically associate inputs with field messages

packages/oruga/src/components/icon/Icon.vue
Fixes #1027
- change type of `component` prop to accept component objects and component constructor functions
=> fix(icon): adjust `component` prop type

packages/oruga/src/components/slider/Slider.vue, packages/oruga/src/components/slider/SliderThumb.vue, packages/oruga/src/components/slider/examples/base.vue, packages/oruga/src/components/slider/props.ts, packages/oruga/src/components/tabs/Tabs.vue
- rename the slider `customFormatter` prop to `formatter` prop to make it consistent with other components.
=> refactor(slider): rename `customFormatter` prop to `formatter` prop

packages/oruga/src/components/slider/tests/__snapshots__/slider.test.ts.snap, packages/oruga/src/components/tooltip/Tooltip.vue, packages/oruga/src/components/tooltip/tests/__snapshots__/tooltip.test.ts.snap
- move trigger element as first child of the tooltip component to match other components
=> refactor(tooltip): move trigger as first child

packages/oruga/package.json, packages/oruga/vite.config.js
Part of #1038
- add `vue-component-type-helpers` as dependency
- added `vue-component-type-helpers` as vite-plugin-dts `bundledPackages` entry, this does not currently work as intended
=> fix(1038): add `vue-component-type-helpers` as dependency

packages/oruga/src/components/loading/Loading.vue, packages/oruga/src/components/loading/tests/__snapshots__/loading.test.ts.snap, packages/oruga/src/components/modal/Modal.vue, packages/oruga/src/components/modal/tests/__snapshots__/modal.test.ts.snap, packages/oruga/src/components/sidebar/Sidebar.vue
Fixes #1039
- remove unnecessary `aria-hidden="true"` on modal, sidebar and loading overlays
=> fix(a11y): remove unnecessary `aria-hidden="true"` on  overlays

packages/oruga/src/components/datepicker/DatepickerTableRow.vue
- add missing `effectScope` to defineClasses
=> fix(datepicker): add missing `effectScope` to defineClasses

packages/docs/.vitepress/theme/components/ThemeSelector.vue, packages/docs/.vitepress/theme/layout/Layout.vue
- The bulma theme has an automatic detection of the environment color specification, but vitpress and the other themes don't. So we force the bulma theme to use light mode.
=> docs: add `theme-light` specification

packages/oruga/src/components/modal/props.ts, packages/oruga/src/components/notification/props.ts, packages/oruga/src/components/sidebar/props.ts, packages/oruga/src/components/steps/props.ts, packages/oruga/src/components/tabs/props.ts, packages/oruga/src/types/utils.ts
- create a custom `ComponentEmits` helper which defines the emits of an component as object. Because the `ComponentEmit` from "vue-component-type-helpers" does not export the emits as an object but as: `((event: "close", ...args: any[]) => void) | undefined`
=> fix(programmatic): solve wrong `events` prop type

packages/oruga/src/components/field/Field.vue, packages/oruga/src/components/field/fieldInjection.ts
- add a unique id to the label of the Field component
- add the labelId to tje injection data for inputs
=> feat(field): add unique label Id to field injection

packages/oruga/src/components/field/Field.vue, packages/oruga/src/components/field/fieldInjection.ts, packages/oruga/src/components/steps/StepItem.vue, packages/oruga/src/components/steps/Steps.vue, packages/oruga/src/components/steps/types.ts, packages/oruga/src/components/table/TableColumn.vue, packages/oruga/src/components/tabs/TabItem.vue, packages/oruga/src/components/tabs/Tabs.vue, packages/oruga/src/components/tabs/tests/tabs.integration.test.ts, packages/oruga/src/components/tabs/types.ts, packages/oruga/src/composables/useParentProvider.ts
- add better `useParentProvider` typings
=> refactor: enhance `useParentProvider` types

packages/oruga/src/components/table/Table.vue
Fixes #1141
- switch Table reactive class bind apply trigger for `mobileClass` root class
=> fix(table): solve `mobileClass` issue

packages/oruga/src/components/autocomplete/Autocomplete.vue, packages/oruga/src/components/carousel/Carousel.vue, packages/oruga/src/components/dropdown/Dropdown.vue, packages/oruga/src/components/loading/Loading.vue, packages/oruga/src/components/modal/Modal.vue, packages/oruga/src/components/sidebar/Sidebar.vue, packages/oruga/src/components/tooltip/Tooltip.vue, packages/oruga/src/components/utils/PickerWrapper.vue, packages/oruga/src/composables/tests/useClickOutside.test.ts, packages/oruga/src/composables/tests/useEventListener.test.ts, packages/oruga/src/composables/useClickOutside.ts, packages/oruga/src/composables/useEventListener.ts, packages/oruga/src/composables/useMatchMedia.ts
-  update `useEventListener` composable
-  update `useClickOutside` composable
=> refactor: update `useEventListener` composable

packages/oruga/src/components/checkbox/Checkbox.vue, packages/oruga/src/components/radio/Radio.vue, packages/oruga/src/components/switch/Switch.vue
- Corrected a formula calculation: the labelId now correctly checks the default slot instead of a non-existing label slot.
=> fix(checkbox|radio|switch): correct formula issues with label slot

packages/oruga/src/components/table/TableColumn.vue, packages/oruga/src/composables/useParentProvider.ts
Fixes #1160
- Update the `data-id` property of the root template of the TableColumn component to follow the convention that allows proper columns to be sorted by template order by the `useParentProvider` composable.
=> fix(table): solve a table column ordering problem

packages/docs/components/Slider.md, packages/oruga/src/components/slider/SliderThumb.vue, packages/oruga/src/components/slider/SliderTick.vue, packages/oruga/src/components/slider/examples/tick-and-label.vue
- add `aria-labelledby` with the field wrapper label id to the slider thumb element
- fix examples
=> feat(slider): add slider thumb aria-labelledby connection to the field wrapper

packages/oruga/src/components/steps/StepItem.vue, packages/oruga/src/components/tabs/TabItem.vue, packages/oruga/src/components/tabs/tests/tabs.test.ts
Fixes #1159
- The bug only occurs if the `value` prop represents a falsly value, aka `null`, `NaN`, `0`, `""` or `undefined`. This is due to the line `props.value || useId()`. I will update this to `props.value ?? useId()` so that now the `value` will only be a unique id if the value is nullish, aka `null` or `undefined`.
=> fix(tabs|steps): replace falsly check with nullish check for default `value` prop

packages/oruga/src/components/loading/props.ts, packages/oruga/src/components/modal/props.ts, packages/oruga/src/components/sidebar/props.ts
- add internal `container` property for programmatic components so the prop will not be added to $attrs and applied do component template
=> refacor(programmatic): add internal `container` property for programmatic components

packages/oruga/src/components/table/Table.vue, packages/oruga/src/components/table/examples/detailed.vue
Fixes #1216
- Changes `<transition>` into `<transition-group>` in the `Table` component. This fixes opening a custom detail view for a row that includes more than one row.
=> fix(table): use transition-group instead of transition for detail slot

packages/oruga/src/components/carousel/Carousel.vue, packages/oruga/src/components/carousel/CarouselItem.vue, packages/oruga/src/components/dropdown/DropdownItem.vue
- Switch from deprecated keydpress to keydown
- Add missing keydown space handler for "butto" type elements
=> refactor: switch from deprecated keypress to keydown

packages/oruga/src/components/autocomplete/Autocomplete.vue, packages/oruga/src/components/autocomplete/tests/autocomplete.test.ts
- Do not open an empty dropdown when `openOnFocus` is set
=> fix(autocomplete): do not open dropdown when `openOnFocus` and empty options

packages/oruga/src/components/table/Table.vue, packages/oruga/src/components/table/examples/pagination.vue, packages/oruga/src/components/table/tests/table.test.ts
Fixes #1243 
- fix visible row cap calculation
=> fix(table): show correct amount of rows when paginated

packages/oruga/src/components/input/Input.vue, packages/oruga/src/components/input/tests/input.test.ts
Fixes #1250
- include null check for modelValue parsing even the type is only `undefined`
=> fix(input): include `null` check for modelValue parsing

packages/oruga/src/components/table/Table.vue, packages/oruga/src/composables/useOptions.ts
Fixes #1254
- correct the sort behavior when paginated and not backend sorted
- do not only sort one page - sort over the whole data set
=> fix(table): solve sort ordering when paginated

packages/oruga/src/components/sidebar/examples/index.vue
I heard you like small PRs. This fixes a two character spelling error.
=> docs: correct typo

packages/oruga/src/components/tabs/examples/base.vue, packages/oruga/src/components/tabs/examples/expanded.vue, packages/oruga/src/components/tabs/examples/long-header.vue, packages/oruga/src/components/tabs/examples/position.vue, packages/oruga/src/components/tabs/examples/sizes.vue, packages/oruga/src/components/tabs/examples/types.vue, packages/oruga/src/components/tabs/examples/vertical.vue
Our tab examples feature very reasonable content. Unfortunately, we do not live in a reasonable world and our components should work as well as can be expected even when our users do unreasonable things. This PR adds some examples to the docs which expose a few edge case bugs in our themes.
- Adds tabs to makes most examples show a mixture of tabs with and without icons to test for height bugs.
- Adds one tab with content which is much longer with no BRs to test wrapping etc when height changes.
Tab height issues at medium/large size
Vertical tab collapses with large content
https://github.com/user-attachments/assets/10644340-05ea-4b04-be7b-648f804d7413
Tab height issues (not all shown)
Vertical tab wraps with large content
https://github.com/user-attachments/assets/4fbf184f-6666-4d7f-b092 …
=> docs(tab): add additional examples

packages/oruga/src/components/notification/NotificationNotice.vue, packages/oruga/src/components/notification/tests/useNotificationProgrammatic.test.ts
Fixes #1282
If you check the docs, the notification page has this code which should open a success notification.
```
oruga.notification.open({
message: "Something happened correctly!",
variant: "success",
closable: true,
});
```
This code successfully sets closeable and message but it does not pass variant from the notification notice to the notification, which results in a grey default toast rather than the desired green success toast. Previous versions of Oruga (0.8.x and below) bound the notice's props to the notification by default, which passed along variant. 0.9.x instead binds `$attrs`, which does not contain variant.
To solve this problem I've added a daisy-chain to pass only variant down rather. This is not a particularly elegant solution but I'd rather stick to something …
=> fix(notification): solve programmatic does not pass variant to notification

packages/oruga/src/components/table/Table.vue, packages/oruga/src/components/table/tests/__snapshots__/table.test.ts.snap
Fixes #1276
- readd missing `data-label` for table column default slot
=> fix(table): solve column labels are lost on mobile cards

.github/workflows/build.yml, .github/workflows/commit-lint.yml, .github/workflows/gen-check.yml, .github/workflows/publish-pre-release.yml, .github/workflows/publish-release.yml, .github/workflows/test.yml, .github/workflows/ts-check.yml, package-lock.json, packages/oruga/.gitignore, packages/oruga/package.json, packages/oruga/src/__tests__/vitest.setup.ts, packages/oruga/src/components/autocomplete/tests/Autocomplete.browser.test.ts, packages/oruga/src/components/button/tests/Button.browser.test.ts, packages/oruga/src/components/collapse/tests/Collapse.browser.test.ts, packages/oruga/tsconfig.vitest.json, packages/oruga/vite.config.ts
- Tests now include browser tests using Playwright.
- The old Cypress tests are now ported to Playwright.
This establishes a basic browser test framework that we can use to validate complicated UI behavior, e.g. HTML constraint validation.
=> test: add Playwright browser tests

packages/oruga/src/components/loading/Loading.vue, packages/oruga/src/components/loading/tests/useLoadingProgrammatic.test.ts, packages/oruga/src/components/modal/Modal.vue, packages/oruga/src/components/modal/tests/useModalProgrammatic.test.ts, packages/oruga/src/components/notification/NotificationNotice.vue, packages/oruga/src/components/notification/tests/useNotificationProgrammatic.test.ts, packages/oruga/src/components/programmatic/tests/useProgrammatic.test.ts, packages/oruga/src/components/sidebar/Sidebar.vue, packages/oruga/src/components/sidebar/tests/useSidebarProgrammatic.test.ts
Fixes #1305
- spread the close event arguments while emitting the `close` event.
- fix comment typo
- update tests
=> fix(programmatic): resolve inconsistent `close` event args

packages/docs/.vitepress/theme/index.ts, packages/oruga/src/components/button/Button.vue, packages/oruga/src/components/button/props.ts, packages/oruga/src/components/carousel/Carousel.vue, packages/oruga/src/components/icon/Icon.vue, packages/oruga/src/components/icon/examples/base.vue, packages/oruga/src/components/icon/props.ts, packages/oruga/src/components/icon/tests/__snapshots__/icon.test.ts.snap, packages/oruga/src/components/input/Input.vue, packages/oruga/src/components/loading/Loading.vue, packages/oruga/src/components/modal/Modal.vue, packages/oruga/src/components/notification/Notification.vue, packages/oruga/src/components/pagination/Pagination.vue, packages/oruga/src/components/select/Select.vue, packages/oruga/src/components/steps/Steps.vue, packages/oruga/src/components/table/Table.vue, packages/oruga/src/components/table/TableMobileSort.vue, packages/oruga/src/components/tag/Tag.vue, packages/oruga/src/components/tag/tests/__snapshots__/tag.test.ts.snap, packages/oruga/src/components/taginput/Taginput.vue, packages/oruga/src/types/config.ts, packages/oruga/src/utils/icons.ts
- remove `both` prop from icon component
- remove `icon-both` prop from button component
- add internal `environment` variable to the config object
=> refactor(icon): replace internal `both` prop with global config

packages/oruga/src/components/autocomplete/Autocomplete.vue, packages/oruga/src/components/checkbox/Checkbox.vue, packages/oruga/src/components/datetimepicker/Datetimepicker.vue, packages/oruga/src/components/input/Input.vue, packages/oruga/src/components/radio/Radio.vue, packages/oruga/src/components/select/Select.vue, packages/oruga/src/components/switch/Switch.vue, packages/oruga/src/components/taginput/Taginput.vue, packages/oruga/src/components/upload/Upload.vue, packages/oruga/src/components/utils/PickerWrapper.vue, packages/oruga/src/composables/tests/useInputHandler.browser.test.ts
There are some cases where it's useful, such as asynchronous validation.
- Inputs now expose a `checkHtml5Validity` method that is callable through a `ref`.
=> feat(input): expose `checkHtml5Validity` method

packages/oruga/src/components/field/Field.vue
- prevent setting `aria-describedby` when no message is displayed
=> fix(field): prevent setting `aria-describedby` when no message is displayed

packages/oruga/src/components/taginput/Taginput.vue
Fixes #1339 
- pass `variant` as prop to internal Tag component
=> fix(taginput): use variant as tag prop

packages/oruga/src/components/table/Table.vue, packages/oruga/src/components/table/tests/table.test.ts
Fixes #1352
- hide detail row when parent row got hidden
=> fix(table): hide detail row when parent row got hidden

packages/oruga/src/components/autocomplete/tests/__snapshots__/autocomplete.test.ts.snap, packages/oruga/src/components/datepicker/tests/__snapshots__/datepicker.test.ts.snap, packages/oruga/src/components/datetimepicker/tests/__snapshots__/datetimepicker.test.ts.snap, packages/oruga/src/components/dropdown/Dropdown.vue, packages/oruga/src/components/dropdown/DropdownItem.vue, packages/oruga/src/components/dropdown/tests/__snapshots__/dropdown.test.ts.snap, packages/oruga/src/components/taginput/tests/__snapshots__/taginput.test.ts.snap, packages/oruga/src/components/timepicker/tests/__snapshots__/timepicker.test.ts.snap
- add `tabindex="-1"` to dropdown-item
- remove `aria-hidden` attribute when selectable
Reason: 
```
Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive  
technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which 
will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at  https://w3c.github.io/aria/#aria-hidden.
Element with focus: <div.dropdown-menu position-bottom-left fade-leave-from fade-leave-active#v-8>
Ancestor with aria-hidden: <div.dropdown-menu position-bottom-left fade-leave-from fade-leave-active#v-8> 
```
=> fix(dropdown): update a11y attributes

packages/oruga/src/components/breadcrumb/BreadcrumbItem.vue, packages/oruga/src/components/carousel/CarouselItem.vue, packages/oruga/src/components/dropdown/Dropdown.vue, packages/oruga/src/components/dropdown/DropdownItem.vue, packages/oruga/src/components/dropdown/types.ts, packages/oruga/src/components/menu/MenuItem.vue, packages/oruga/src/components/slider/SliderTick.vue, packages/oruga/src/components/steps/StepItem.vue, packages/oruga/src/components/steps/Steps.vue, packages/oruga/src/components/table/Table.vue, packages/oruga/src/components/table/TableColumn.vue, packages/oruga/src/components/table/types.ts, packages/oruga/src/components/tabs/TabItem.vue, packages/oruga/src/components/tabs/Tabs.vue, packages/oruga/src/composables/useParentProvider.ts, packages/oruga/src/composables/useScrollHelper.ts, packages/oruga/src/index.ts
- Always make the root element of an provider child item available to the provider parent
=> refactor(useProviderChild): add root element to provider child

package-lock.json, packages/docs/.vitepress/theme/index.ts, packages/docs/package.json, packages/examples/package.json, packages/oruga/src/components/icon/Icon.vue, packages/oruga/src/types/config.ts, packages/oruga/src/utils/icons.ts
Fixes #1388 
- remove internal `environment` config
- define internal icons based on the icon pack
- update fontawesome dependency
=> fix(icon): transform internal icons based on the icon pack

packages/oruga/src/components/table/Table.vue, packages/oruga/src/components/table/TableColumn.vue, packages/oruga/src/components/table/props.ts, packages/oruga/src/components/table/types.ts, packages/oruga/src/components/utils/SlotComponent.ts
- update SlotComnponent typing
- remove unsessary `$instance` from TableColumn provided data
- strongly type the `thClasses` variable to prevent circular type dependency because `parent` is used in the definition of any class and the variable is used by the parent
=> refactor(table): prevent circular type dependency

packages/oruga/src/components/autocomplete/Autocomplete.vue, packages/oruga/src/components/autocomplete/examples/inspector.vue, packages/oruga/src/components/autocomplete/props.ts, packages/oruga/src/components/types.ts
- rename class `itemGroupTitleClass` to `itemGroupClass` to unify class namings
BREAKING CHANGE: rename class `itemGroupTitleClass` to `itemGroupClass`
=> feat(autocomplete): rename class `itemGroupTitleClass` to `itemGroupClass`

packages/oruga/src/components/carousel/Carousel.vue, packages/oruga/src/components/carousel/examples/slideshow.vue, packages/oruga/src/components/carousel/props.ts, packages/oruga/src/components/types.ts
- make carousel slide wrapper tabable when no indicators are available
=> fix(carousel): solve tab navigation issues when has no indicators
